# Generated by Django 5.1.3 on 2024-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filme",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ANALISES", "Análises"),
                    ("PROGRAMACAO", "Programação"),
                    ("APRESENTACAO", "Apresentação"),
                    ("INTELIGENCIA ARTIFICIAL", "Inteligência Artificial"),
                    ("COMPUTACAO EM NUVEM", "Computação em Nuvem"),
                    ("ADMINISTRACAO", "Administração"),
                    ("OUTROS", "Outros"),
                ],
                max_length=25,
            ),
        ),
    ]
